version: "3"

services:
  api:
    build: .
    ports:
      - "3002:3002"
    environment:
      - MYSQL_HOST=db
      - MYSQL_PORT=3306
      - MYSQL_USER=root
      - MYSQL_PASSWORD=your_mysql_password
      - MYSQL_DATABASE=your_database_name
    depends_on:
      - db

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_password
      MYSQL_DATABASE: your_database_name
    ports:
      - "3303:3306"
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    environment:
      - PMA_HOST=db
      - PMA_PORT=3306
      - MYSQL_ROOT_PASSWORD=your_mysql_password
    ports:
      - "3004:80" # Map port 8080 on host to port 80 on phpMyAdmin container