name: Build and Deploy Full-stack App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Install MySQL client for interacting with the database
      - name: Install MySQL client
        run: sudo apt-get install -y mysql-client

      # Setup Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run database migrations
      # - name: Run database migrations
      #   run: npm run migrate

      # Build and run API
      - name: Build and run API
        run: npm start

      # Deploy full-stack application using Docker Compose
      - name: Deploy Full-stack Application
        run: docker-compose -f docker-compose.yaml up -d
